name : my_recipe
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    #image: rphydra/myrecipe:latest
    ports:
      - 8443:8443
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://roach1:26257,roach2:26258/defaultdb?sslmode=disable&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory&accounting?targetServerType=preferSlave&loadBalanceHosts=true
    command: [ "./wait-for-it.sh", "roach1:26257", "--", "java", "-jar", "app.jar" ]
    restart: on-failure
  #  web2:
  #    build:
  #      context: ..
  #      dockerfile: docker/Dockerfile
  #    #image: rphydra/myrecipe:latest
  #    ports:
  #      - 8442:8443
  #      - 8079:8080
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://roach2:26258/defaultdb?sslmode=disable&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
  #    command: [ "./wait-for-it.sh", "roach2:26258", "--", "java", "-jar", "app.jar" ]
  #    restart: on-failure

  roach1:
    image: cockroachdb/cockroach:v20.2.0
    #still to add docker exec -it roach1 ./cockroach --host=roach1:26357 init --insecure
    command: start --advertise-addr=roach1:26357 --http-addr=roach1:8081 --listen-addr=roach1:26357 --sql-addr=roach1:26257 --insecure --join=roach1:26357,roach2:26357
    ports:
      - "26257:26257"
      - "8081:8081"
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
  roach2:
    image: cockroachdb/cockroach:v20.2.0
    command: start --advertise-addr=roach2:26357 --http-addr=roach2:8082 --listen-addr=roach2:26357 --sql-addr=roach2:26258 --insecure --join=roach1:26357,roach2:26357
    ports:
      - "26258:26258"
      - "8082:8082"
    volumes:
      - ./cockroach-data/roach2:/cockroach/cockroach-data

  roachClusterInit:
    image: cockroachdb/cockroach:v20.2.0
    command: --host=roach1:26357 init --insecure
    depends_on:
      - roach1
      - roach2
